import 'package:flutter/material.dart';

//
//
//
//
//
//
//
//
//
//
//
Map<dynamic, dynamic> json = {
  'Category': [
    'Pets',
    'Vehicles',
    'Properties',
    'Electronics',
    'Home Appliances',
    'Kitchen Appliances',
    'Fashion',
    'Sports',
    'Furniture',
    'Arts and Antiques',
    'Books, Papers and Posters',
    'Musical Instruments',
    'Machines',
    'Services',
    'Business for Sale & Investments',
    'Memberships and Tickets',
    'Jobs'
  ],
  'Pets': {
    'subcategory': ['Foods', 'Pet type', 'House', 'Other'],
    'Foods': ['Animal', 'Brand', 'Condition'],
    'Pet type': ['Animal', 'Bread', 'Age'],
    'House': ['Animal', 'Condition'],
    'Other': ['Animal', 'Bread', 'Age']
  },
  'Vehicles': {
    'subcategory': [
      'Cars',
      'Bikes',
      'Electric Cars',
      'Electric Bikes',
      'Cycle',
      'Autos',
      'Van',
      'Lorries',
      'Tractors',
      'Buses',
      'Other',
    ],
    "Cars": [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    "Bikes": [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    'Electric Cars': [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    'Electric Bikes': [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    'Cycle': [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    'Autos': [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    'Van': [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    'Lorries': [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    'Tractors': [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    'Buses': [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    'Other': [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ]
  },
  'Properties': {
    'subcategory': [
      'Plot/Land',
      'Flat',
      'House/Villa',
      'Agriculture',
      'Commercial',
    ],
    'Plot/Land': [
      'Post for',
      'Facing',
      'Lenght',
      'Breadth',
      'Area',
      'Amenities',
      'Nearby',
      'Registration',
      'Distance form main Road',
      'Front Road',
      'Facing Road Width',
    ],
    'Flat': [
      'Post for',
      'Facing',
      'Lenght',
      'Breadth',
      'Area',
      'Carpet area0',
      'Beds',
      'Baths',
      'Furnishing',
      'Balcony',
      'Gated community'
          'Property floor no',
      'Number of Floors',
      'Car parkings',
      'Bike Parkings',
      'Amenities',
      'Nearby',
      'Registration',
      'Distance form main Road',
      'Front Road',
      'Facing Road Width',
    ],
    'House/Villa': [
      'Post for',
      'Facing',
      'Lenght',
      'Breadth',
      'Area',
      'Carpet area0',
      'Beds',
      'Baths',
      'Furnishing',
      'Balcony',
      'Gated community'
          'Property floor no',
      'Number of Floors',
      'Car parkings',
      'Bike Parkings',
      'Amenities',
      'Nearby',
      'Registration',
      'Distance form main Road',
      'Front Road',
      'Facing Road Width',
    ],
    'Agriculture': [
      'Post for',
      'Facing',
      'Area',
      'Nearby',
      'Registration',
      'Distance form main Road',
      'Front Road',
      'Facing Road Width',
    ],
    'Commercial': [
      'For sale',
      'Post for',
      'Facing',
      'Lenght',
      'Breadth',
      'Area',
      'Carpet area0',
      'Beds',
      'Baths',
      'Furnishing',
      'Balcony',
      'Gated community'
          'Property floor no',
      'Number of Floors',
      'Car parkings',
      'Bike Parkings',
      'Amenities',
      'Nearby',
      'Registration',
      'Distance form main Road',
      'Front Road',
      'Facing Road Width',
    ]
  },
  'Electronics': {
    'subcategory': [
      'Mobiles',
      'Laptops',
      'Tvs',
      'Desktops',
      'Cameras',
      'Drones',
      'Go pro',
      'Watches',
      'Accessories',
      'Other',
    ],
    'Mobiles': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year'],
    'Laptops': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year'],
    'Tvs': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year'],
    'Desktops': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year'],
    'Cameras': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year'],
    'Drones': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year'],
    'Go pro': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year'],
    'Watches': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year'],
    'Accessories': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year'],
    'Others': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year']
  },
  'Home Appliances': {
    'subcategory': [
      'Fridge',
      'Microwave',
      'Washing Machine',
      'Air Conditioners',
      'Geysers',
      'Fans',
      'Inverters',
      'Batteries',
      'Other',
    ],
    "Fridge": ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Microwave': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Washing Machine': [
      'Name',
      'Brand',
      'Details',
      'Condition',
      'Color',
      'Year'
    ],
    'Air Conditioners': [
      'Name',
      'Brand',
      'Details',
      'Condition',
      'Color',
      'Year'
    ],
    'Getsers': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Fans': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Inverters': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Batteries': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Other': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
  },
  'Kitchen Appliances': {
    'subcategory': [
      'Water Purifier',
      'Dish Washer',
      ' Mixer',
      'Grinder',
      'Juicer',
      'Electric Cooker',
      'General Cooker',
      'Coffee Maker',
      'Other',
    ],
    'Water Purifier': [
      'Name',
      'Brand',
      'Details',
      'Condition',
      'Color',
      'Year'
    ],
    'Dish Washer': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Mixer': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Grinder': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Juicer': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Electric Cooker': [
      'Name',
      'Brand',
      'Details',
      'Condition',
      'Color',
      'Year'
    ],
    'Coffee Maker': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Other': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
  },
  'Fashion': {
    'subcategory': [
      'Watches',
      'Jackets',
      'Shoes',
      ' Dresses',
      'Jewellery',
      'Bags',
      'Bag Packs',
      'Belts',
      'Sunglasses',
      'Wallets',
      'Hats',
      'Other',
    ],
    'Watches': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Jackets': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Shoes': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    ' Dresses': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Jewellery': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Bags': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Bag Packs': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Belts': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Sunglasses': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Wallets': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Hats': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Other': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
  },
  'Sports': {
    'subcategory': [
      'Outdoor',
      'Fitness',
      'Team',
      'Water',
      'Target',
      'Rollers',
      'Other',
    ],
    'Outdoor': [
      'Type',
      'Name',
      'Brand',
      'Details',
      'Condition',
      'Color',
      'Year'
    ],
    'Fitness': [
      'Type',
      'Name',
      'Brand',
      'Details',
      'Condition',
      'Color',
      'Year'
    ],
    'Team': ['Type', 'Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Water': ['Type', 'Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Target': [
      'Type',
      'Name',
      'Brand',
      'Details',
      'Condition',
      'Color',
      'Year'
    ],
    'Rollers': [
      'Type',
      'Name',
      'Brand',
      'Details',
      'Condition',
      'Color',
      'Year'
    ],
    'Other': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
  },
  'Furniture': {
    'subcategory': [
      'Sofa',
      'Beds',
      'Mattress',
      'Chairs',
      'Office Tables',
      'Dining Tables',
      'Cupboards',
      'Other',
    ],
    'Sofa': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Beds': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Mattress': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Chairs': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Office Tables': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Dining Tables': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Cupboards': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Other': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
  },
  'Arts and Antiques': {
    'subcategory': [
      'Sketching',
      'Stencils',
      'Oil Painting',
      'Water Painting',
      'Antiques',
      'Coins',
      'Stamps',
      'Other',
    ],
    'Sketching': ['Condition', 'How old is it ?'],
    'Stencils': ['Condition', 'How old is it ?'],
    'Oil Painting': ['Condition', 'How old is it ?'],
    'Water Painting': ['Condition', 'How old is it ?'],
    'Antiques': ['Condition', 'How old is it ?'],
    'Coins': ['Condition', 'How old is it ?'],
    'Stamps': ['Condition', 'How old is it ?'],
    'Other': ['Condition', 'How old is it ?'],
  },
  'Books, Papers and Posters': {
    'subcategory': [
      'Academic',
      'Children',
      'Novels',
      'Old Papers',
      'Old Comics',
      'Posters',
    ],
    'Academic': ['Condition', 'Name', 'Author/Publisher', 'How old is it ?'],
    'Children': ['Condition', 'Name', 'Author/Publisher', 'How old is it ?'],
    'Novels': ['Condition', 'Name', 'Author/Publisher', 'How old is it ?'],
    'Old Papers': ['Condition', 'Name', 'Author/Publisher', 'How old is it ?'],
    'Old Comics': ['Condition', 'Name', 'Author/Publisher', 'How old is it ?'],
    'Posters': ['Condition', 'Name', 'Author/Publisher', 'How old is it ?'],
  },
  'Musical Instruments': {
    'subcategory': [
      'Guitar',
      'Keyboard',
      'Drums',
      'Piano',
      'Flute',
      'Trumpet',
      'Violin',
      'Sitar',
      'Bongo',
      'Saxophone',
      'harmonica',
      'Accordion',
      'Bugle',
      'Clarinet',
      'Tabla',
      'Sehnai',
      'Mridangam',
      'Other',
    ],
    'Guitar': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Keyboard': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Drums': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Piano': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Flute': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Trumpet': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Violin': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Sitar': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Bongo': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Saxophone': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'harmonica': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Accordion': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Bugle': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Clarinet': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Tabla': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Sehnai': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Mridangam': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Other': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
  },
  'Machines': {
    'subcategory': [
      'Medical',
      'Agricultural',
      'Industrial',
      'Electrical',
      'Mechanical',
      'Construction',
      'Other',
    ],
    'Medical': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Agricultural': [
      'Name',
      'Brand',
      'Details',
      'Condition',
      'How old is it ?'
    ],
    'Industrial': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Electrical': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Mechanical': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Construction': [
      'Name',
      'Brand',
      'Details',
      'Condition',
      'How old is it ?'
    ],
    'Other': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
  },
  'Services': {
    'subcategory': [
      'Coaching',
      'Technical Services',
      'Electrical Services',
      'Software',
      'other',
    ],
    'Coaching': ['Experience', 'Skills'],
    'Technical Services': ['Experience', 'Skills'],
    'Electrical Services': ['Experience', 'Skills'],
    'Software': ['Experience', 'Skills'],
    'other': ['Experience', 'Skills'],
  },
  'Business for Sale & Investments': {
    'subcategory': [
      'Sale',
      'Pre launch Investments',
      'Partnership',
    ],
    'Sale': ['Business Name', 'Business type', 'How old is it ?'],
    'Pre launch Investments': ['Business Name', 'Business type'],
    'Partnership': ['Business Name', 'Business type', 'How old is it ?'],
  },
  'Memberships and Tickets': {
    'subcategory': [
      'Event Tickets',
      'Tickets',
      'Memberships',
    ],
    'Event Tickets': ['Name', 'Date'],
    'Tickets': ['Name', 'Date'],
    'Memberships': ['Name', 'Purchase Date', 'Expire data'],
  },
  'Jobs': {
    'subcategory': [
      'Teacher',
      'Software',
      'Accountant',
      'Designer',
      'Sales & Marketing',
      'Office Assistant',
      'Driver',
      'Cook',
      'Security Guards',
      'other',
    ],
    'Teacher': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
    'Software': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
    'Accountant': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
    'Designer': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
    'Sales & Marketing': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
    'Office Assistant': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
    'Driver': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
    'Cook': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
    'Security Guards': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
    'other': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
  }
};

// Jobs
// Location (Required) - TextField
// Type (Required) - Jobs {Teacher, Software, Accountant, Designer, Sales & Marketing, Office Assistant, Driver, Cook, Security Guards,other }
// Company Name (Required) - TextField
// Company Website (Required) - TextField
// Job Location (Required) - TextField
// Education (Required) - TextField
// Experience (Required) - TextField
// Skills (Required) - TextField
// Salary (Required) - TextField
// Job Type (Required) - TextField {Full Time, Part Time, Contract}
// Description (Optional) - Text field - Voice Input as well - Max characters - 1000 characters
// Special Mentions (Optional) - Textfield - Condition that max 8-10 Keywords separated by comma
// Tiles - Location, Type(Sub-Category), Salary, Experience

Map PostJson = {
  'Pets': {
    'subcategory': ['Foods', 'Pet type', 'House', 'Other'],
    'Foods': ['Animal', 'Brand', 'Condition'],
    'Pet type': ['Animal', 'Bread', 'Age'],
    'House': ['Animal', 'Condition'],
    'Other': ['Animal', 'Bread', 'Age']
  },
  'Vehicles': {
    'subcategory': [
      'Cars',
      'Bikes',
      'Electric Cars',
      'Electric Bikes',
      'Cycle',
      'Autos',
      'Van',
      'Lorries',
      'Tractors',
      'Buses',
      'Other',
    ],
    "Cars": [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    "Bikes": [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    'Electric Cars': [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    'Electric Bikes': [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    'Cycle': [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    'Autos': [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    'Van': [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    'Lorries': [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    'Tractors': [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    'Buses': [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ],
    'Other': [
      'Make',
      'Model & Trim',
      'Color',
      'Condition',
      'Transmission',
      'Year of Make',
      'Year of Purchase',
      'Mileage',
      'Number of Owners',
      'Number of Accidents',
      'Vehicle Registered at',
      'Vehicle Present at',
    ]
  },
  'Properties': {
    'subcategory': [
      'Plot/Land',
      'Flat',
      'House/Villa',
      'Agriculture',
      'Commercial',
    ],
    'Plot/Land': [
      'Post for',
      'Facing',
      'Lenght',
      'Breadth',
      'Area',
      'Amenities',
      'Nearby',
      'Registration',
      'Distance form main Road',
      'Front Road',
      'Facing Road Width',
    ],
    'Flat': [
      'Post for',
      'Facing',
      'Lenght',
      'Breadth',
      'Area',
      'Carpet area0',
      'Beds',
      'Baths',
      'Furnishing',
      'Balcony',
      'Gated community'
          'Property floor no',
      'Number of Floors',
      'Car parkings',
      'Bike Parkings',
      'Amenities',
      'Nearby',
      'Registration',
      'Distance form main Road',
      'Front Road',
      'Facing Road Width',
    ],
    'House/Villa': [
      'Post for',
      'Facing',
      'Lenght',
      'Breadth',
      'Area',
      'Carpet area0',
      'Beds',
      'Baths',
      'Furnishing',
      'Balcony',
      'Gated community'
          'Property floor no',
      'Number of Floors',
      'Car parkings',
      'Bike Parkings',
      'Amenities',
      'Nearby',
      'Registration',
      'Distance form main Road',
      'Front Road',
      'Facing Road Width',
    ],
    'Agriculture': [
      'Post for',
      'Facing',
      'Area',
      'Nearby',
      'Registration',
      'Distance form main Road',
      'Front Road',
      'Facing Road Width',
    ],
    'Commercial': [
      'For sale',
      'Post for',
      'Facing',
      'Lenght',
      'Breadth',
      'Area',
      'Carpet area0',
      'Beds',
      'Baths',
      'Furnishing',
      'Balcony',
      'Gated community'
          'Property floor no',
      'Number of Floors',
      'Car parkings',
      'Bike Parkings',
      'Amenities',
      'Nearby',
      'Registration',
      'Distance form main Road',
      'Front Road',
      'Facing Road Width',
    ]
  },
  'Electronics': {
    'subcategory': [
      'Mobiles',
      'Laptops',
      'Tvs',
      'Desktops',
      'Cameras',
      'Drones',
      'Go pro',
      'Watches',
      'Accessories',
      'Other',
    ],
    'Mobiles': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year'],
    'Laptops': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year'],
    'Tvs': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year'],
    'Desktops': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year'],
    'Cameras': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year'],
    'Drones': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year'],
    'Go pro': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year'],
    'Watches': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year'],
    'Accessories': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year'],
    'Others': ['Device' 'Name', 'Brand', 'Condition', 'Color', 'Year']
  },
  'Home Appliances': {
    'subcategory': [
      'Fridge',
      'Microwave',
      'Washing Machine',
      'Air Conditioners',
      'Geysers',
      'Fans',
      'Inverters',
      'Batteries',
      'Other',
    ],
    "Fridge": ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Microwave': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Washing Machine': [
      'Name',
      'Brand',
      'Details',
      'Condition',
      'Color',
      'Year'
    ],
    'Air Conditioners': [
      'Name',
      'Brand',
      'Details',
      'Condition',
      'Color',
      'Year'
    ],
    'Getsers': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Fans': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Inverters': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Batteries': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Other': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
  },
  'Kitchen Appliances': {
    'subcategory': [
      'Water Purifier',
      'Dish Washer',
      ' Mixer',
      'Grinder',
      'Juicer',
      'Electric Cooker',
      'General Cooker',
      'Coffee Maker',
      'Other',
    ],
    'Water Purifier': [
      'Name',
      'Brand',
      'Details',
      'Condition',
      'Color',
      'Year'
    ],
    'Dish Washer': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Mixer': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Grinder': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Juicer': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Electric Cooker': [
      'Name',
      'Brand',
      'Details',
      'Condition',
      'Color',
      'Year'
    ],
    'Coffee Maker': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Other': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
  },
  'Fashion': {
    'subcategory': [
      'Watches',
      'Jackets',
      'Shoes',
      ' Dresses',
      'Jewellery',
      'Bags',
      'Bag Packs',
      'Belts',
      'Sunglasses',
      'Wallets',
      'Hats',
      'Other',
    ],
    'Watches': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Jackets': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Shoes': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    ' Dresses': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Jewellery': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Bags': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Bag Packs': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Belts': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Sunglasses': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Wallets': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Hats': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Other': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
  },
  'Sports': {
    'subcategory': [
      'Outdoor',
      'Fitness',
      'Team',
      'Water',
      'Target',
      'Rollers',
      'Other',
    ],
    'Outdoor': [
      'Type',
      'Name',
      'Brand',
      'Details',
      'Condition',
      'Color',
      'Year'
    ],
    'Fitness': [
      'Type',
      'Name',
      'Brand',
      'Details',
      'Condition',
      'Color',
      'Year'
    ],
    'Team': ['Type', 'Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Water': ['Type', 'Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Target': [
      'Type',
      'Name',
      'Brand',
      'Details',
      'Condition',
      'Color',
      'Year'
    ],
    'Rollers': [
      'Type',
      'Name',
      'Brand',
      'Details',
      'Condition',
      'Color',
      'Year'
    ],
    'Other': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
  },
  'Furniture': {
    'subcategory': [
      'Sofa',
      'Beds',
      'Mattress',
      'Chairs',
      'Office Tables',
      'Dining Tables',
      'Cupboards',
      'Other',
    ],
    'Sofa': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Beds': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Mattress': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Chairs': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Office Tables': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Dining Tables': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Cupboards': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
    'Other': ['Name', 'Brand', 'Details', 'Condition', 'Color', 'Year'],
  },
  'Arts and Antiques': {
    'subcategory': [
      'Sketching',
      'Stencils',
      'Oil Painting',
      'Water Painting',
      'Antiques',
      'Coins',
      'Stamps',
      'Other',
    ],
    'Sketching': ['Condition', 'How old is it ?'],
    'Stencils': ['Condition', 'How old is it ?'],
    'Oil Painting': ['Condition', 'How old is it ?'],
    'Water Painting': ['Condition', 'How old is it ?'],
    'Antiques': ['Condition', 'How old is it ?'],
    'Coins': ['Condition', 'How old is it ?'],
    'Stamps': ['Condition', 'How old is it ?'],
    'Other': ['Condition', 'How old is it ?'],
  },
  'Books, Papers and Posters': {
    'subcategory': [
      'Academic',
      'Children',
      'Novels',
      'Old Papers',
      'Old Comics',
      'Posters',
    ],
    'Academic': ['Condition', 'Name', 'Author/Publisher', 'How old is it ?'],
    'Children': ['Condition', 'Name', 'Author/Publisher', 'How old is it ?'],
    'Novels': ['Condition', 'Name', 'Author/Publisher', 'How old is it ?'],
    'Old Papers': ['Condition', 'Name', 'Author/Publisher', 'How old is it ?'],
    'Old Comics': ['Condition', 'Name', 'Author/Publisher', 'How old is it ?'],
    'Posters': ['Condition', 'Name', 'Author/Publisher', 'How old is it ?'],
  },
  'Musical Instruments': {
    'subcategory': [
      'Guitar',
      'Keyboard',
      'Drums',
      'Piano',
      'Flute',
      'Trumpet',
      'Violin',
      'Sitar',
      'Bongo',
      'Saxophone',
      'harmonica',
      'Accordion',
      'Bugle',
      'Clarinet',
      'Tabla',
      'Sehnai',
      'Mridangam',
      'Other',
    ],
    'Guitar': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Keyboard': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Drums': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Piano': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Flute': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Trumpet': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Violin': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Sitar': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Bongo': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Saxophone': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'harmonica': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Accordion': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Bugle': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Clarinet': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Tabla': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Sehnai': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Mridangam': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Other': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
  },
  'Machines': {
    'subcategory': [
      'Medical',
      'Agricultural',
      'Industrial',
      'Electrical',
      'Mechanical',
      'Construction',
      'Other',
    ],
    'Medical': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Agricultural': [
      'Name',
      'Brand',
      'Details',
      'Condition',
      'How old is it ?'
    ],
    'Industrial': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Electrical': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Mechanical': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
    'Construction': [
      'Name',
      'Brand',
      'Details',
      'Condition',
      'How old is it ?'
    ],
    'Other': ['Name', 'Brand', 'Details', 'Condition', 'How old is it ?'],
  },
  'Services': {
    'subcategory': [
      'Coaching',
      'Technical Services',
      'Electrical Services',
      'Software',
      'other',
    ],
    'Coaching': ['Experience', 'Skills'],
    'Technical Services': ['Experience', 'Skills'],
    'Electrical Services': ['Experience', 'Skills'],
    'Software': ['Experience', 'Skills'],
    'other': ['Experience', 'Skills'],
  },
  'Business for Sale & Investments': {
    'subcategory': [
      'Sale',
      'Pre launch Investments',
      'Partnership',
    ],
    'Sale': ['Business Name', 'Business type', 'How old is it ?'],
    'Pre launch Investments': ['Business Name', 'Business type'],
    'Partnership': ['Business Name', 'Business type', 'How old is it ?'],
  },
  'Memberships and Tickets': {
    'subcategory': [
      'Event Tickets',
      'Tickets',
      'Memberships',
    ],
    'Event Tickets': ['Name', 'Date'],
    'Tickets': ['Name', 'Date'],
    'Memberships': ['Name', 'Purchase Date', 'Expire data'],
  },
  'Jobs': {
    'subcategory': [
      'Teacher',
      'Software',
      'Accountant',
      'Designer',
      'Sales & Marketing',
      'Office Assistant',
      'Driver',
      'Cook',
      'Security Guards',
      'other',
    ],
    'Teacher': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
    'Software': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
    'Accountant': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
    'Designer': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
    'Sales & Marketing': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
    'Office Assistant': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
    'Driver': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
    'Cook': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
    'Security Guards': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
    'other': [
      'Company Name',
      'Company Website',
      'Job Location',
      'Min Qualification',
      'Experience',
      'Skills',
      'Salary',
      'Job Type',
    ],
  }
};
